---
- name: win_chocolatey module demo
  hosts: all
  become: false
  gather_facts: false
  vars:
    - packages:
      - git
      - notepadplusplus
      - office365business
  tasks:
    - name: install packages
      win_chocolatey:
        name: "{{ packages }}"
        state: present
...
