---
- name: win_chocolatey module
  hosts: all
  become: false
  gather_facts: false
  vars:
    - packages:
      - git
      - teamviewer
      - firefox
  tasks:
    - name: install packages
      win_chocolatey:
        name: "{{ packages }}"
        state: present
  tasks:
    - name: remover packages
      win_chocolatey:
        name: notepadplusplus
        state: absent
...

